### ISSUE TITLE
react-native listed as a depency make the metro-bundler bugging

### ISSUE THREAD

**Issue by mehdialouafi** [KumarAbhirup/iconic-input#1]
This might be related to the package.json definition see this [stackoverflow question](https://stackoverflow.com/questions/52566757/internal-error-metro-bundler-has-encountered-an-internal-error-duplicate-modul/52566836?noredirect=1#comment92071174_52566836)

I really be happy to make a PR if you want to (and if it's an actual problem)

**Comment by kumarabhirup** [comment]
Yes. It is an actual problem. I just made a quick update and released the new npm package. I also updated it here on GitHub. Thanks a lot to inform :-)
You saved my project on StackOverflow that fine day ;-)

Please just check and let me know if `package.json` code is right this time.

**Comment by mehdialouafi** [comment]
Hi there, sorry It has been a long / tough week (not finished yet.. 3 hours to go), I will check this this week-end :) 

Thanks for you work @KumarAbhirup
